---
- name: "Monitor / Fluentd / Initialize"
  ansible.builtin.include_tasks:
    file: "mon_fluentd_initialize.yml"

- name: "Monitor / Fluentd / Deploy"
  ansible.builtin.include_tasks:
    file: "mon_fluentd_deploy.yml"
  when:
    - mon_fluentd['deploy'] is defined
    - mon_fluentd['deploy']

- name: "Monitor / Fluentd / Finalize"
  ansible.builtin.include_tasks:
    file: "mon_fluentd_finalize.yml"
...
