---
- name: "Monitor / Fluentd / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ mon_fluentd_application | default('mon_fluentd_application') }})"
    quiet: true
    that:
      - mon_fluentd_application is defined
      - mon_fluentd_application | length > 0
      - mon_fluentd_application['name'] is defined
      - mon_fluentd_application['type'] is defined
      - mon_fluentd_application['version'] is defined
      - mon_fluentd_application['installed'] is defined

- name: "Monitor / Fluentd / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "mon_fluentd_deploy_package.yml"
  when:
    - mon_fluentd_application is defined
...
