---
- name: "Monitor / Fluentd / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ mon_fluentd_application }}"
    sys_package_profiles: "{{ mon_fluentd_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
