---
# Define platform specific paths
mon_fluentd_base:
  paths: "{{ mon_fluentd_base_common['paths'] }}"
  etc: "{{ mon_fluentd_base_common['etc'] }}"
  files: "{{ mon_fluentd_base_common['files'] }}"
  run: "{{ mon_fluentd_base_common['run'] }}"
  templates: "{{ mon_fluentd_base_common['templates'] }}"
  access: "{{ mon_fluentd_base_common['access'] }}"

# Define application package details
mon_fluentd_profiles:
  snap: "{{ mon_fluentd_profiles_common['snap'] }}"
  flatpak: "{{ mon_fluentd_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      origin: "treasuredata"
      packages:
        - name: "td-agent"

# Define custom package repositories
mon_fluentd_repository_custom_yum: []
mon_fluentd_repository_custom_apt:
  - name: "treasuredata"
    suite: "focal"
    component: "contrib"
    url: "http://packages.treasuredata.com/4/ubuntu/focal/"
    pgpkey: "https://packages.treasuredata.com/GPG-KEY-td-agent"

# Set package repositories states
mon_fluentd_repository_catalog_distro: {}
mon_fluentd_repository_catalog_yum: {}
mon_fluentd_repository_catalog_apt:
  treasuredata: true
...
